#pragma once

enum BackgroundMode
{
	BACKGROUND_MODE_SOLID_COLOR,
	BACKGROUND_MODE_GRADIENT,
	BACKGROUND_MODE_TEXTURE
};

enum ControlMode
{
	CONTROL_MODE_FREE_FLY,
	CONTROL_MODE_ORBIT,
};

enum ProjectionMode
{
	PROJECTION_MODE_PERSPECTIVE,
	PROJECTION_MODE_ORTHOGRAPHIC,
	PROJECTION_MODE_THIN_LENS,
};

enum MaterialType
{
	MATERIAL_TYPE_LAMBERTIAN = 0,
	MATERIAL_TYPE_CONDUCTOR,
	MATERIAL_TYPE_DIELECTRIC,
	MATERIAL_TYPE_PRINCIPLED,
	MATERIAL_TYPE_DIFFUSE_LIGHT,
	MATERIAL_TYPE_COUNT
};

enum RayType
{
	RAY_TYPE_RADIANCE = 0,
	RAY_TYPE_SHADOW,
	RAY_TYPE_COUNT
};

enum SamplerType
{
	SAMPLER_TYPE_INDEPENDENT = 0,
	SAMPLER_TYPE_STRATIFIED,
	SAMPLER_TYPE_MULTIJITTER
};

enum IntegratorType
{
	INTEGRATOR_TYPE_BSDF_ONLY = 0,
	INTEGRATOR_TYPE_PATH
};